### ISSUE TITLE
Plugin not recognizing some Behat steps in the integration branch

### ISSUE THREAD

**Issue by dravek** [lmscloud-io/mdlcode-docs#16] opened 2024-08-30 09:06 UTC
I just noticed some Behat steps not recognized in Moodle integration branch. I tried re-indexing but still now working for me.
For example:

1) "**Given the following config values are set as admin:**"
badges/tests/behat/add_badge.feature

2) "**Given the following "core_badges > Badge" exists:**"
"**And the following "core_badges > Criteria" exists:**"
badges/tests/behat/award_badge.feature

**Comment by marinaglancy** [comment] 2024-08-30 19:05
Thanks David
Tihs is caused by https://tracker.moodle.org/browse/MDL-81889  that added #examples to the behat step definitions and now mdlcode parser can no parse them. I will fix it soon

**Comment by marinaglancy** [comment] 2024-09-01 20:03
Thanks again for reporting, @dravek . Fixed in version 1.0.34 released 2024-09-01

**Closed** 2024-09-01 20:04 UTC
